/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;

/**
 *
 * @author oyini
 */
public class LoanApp_W extends javax.swing.JFrame {

    private static final DecimalFormat MONEY_FORMAT = new DecimalFormat("#,##0.00");

    /**
     * Creates new form LoanApp_W
     */
    public LoanApp_W() {
        initComponents();
        setUpTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        loanAmountLabel = new javax.swing.JLabel();
        loanAmountField = new javax.swing.JTextField();
        durationLabel = new javax.swing.JLabel();
        durationField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        scheduleScrollPane = new javax.swing.JScrollPane();
        scheduleTable = new javax.swing.JTable();
        totalRepaymentLabel = new javax.swing.JLabel();
        totalRepaymentField = new javax.swing.JTextField();
        totalInterestLabel = new javax.swing.JLabel();
        totalInterestField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loan Application");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(243, 233, 220));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("LOAN APPLICATION");

        loanAmountLabel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        loanAmountLabel.setText("ENTER LOAN AMOUNT");

        loanAmountField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loanAmountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loanAmountFieldKeyTyped(evt);
            }
        });

        durationLabel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        durationLabel.setText("ENTER DURATION");

        durationField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        durationField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                durationFieldKeyTyped(evt);
            }
        });

        calculateButton.setBackground(new java.awt.Color(224, 224, 224));
        calculateButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        calculateButton.setText("CALCULATE");
        calculateButton.setFocusPainted(false);
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        scheduleTable.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        scheduleTable.setRowHeight(22);
        scheduleScrollPane.setViewportView(scheduleTable);

        totalRepaymentLabel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        totalRepaymentLabel.setText("TOTAL REPAYMENT");

        totalRepaymentField.setEditable(false);
        totalRepaymentField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalRepaymentField.setForeground(new java.awt.Color(64, 64, 64));

        totalInterestLabel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        totalInterestLabel.setText("TOTAL INTEREST");

        totalInterestField.setEditable(false);
        totalInterestField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalInterestField.setForeground(new java.awt.Color(64, 64, 64));

        clearButton.setBackground(new java.awt.Color(204, 0, 0));
        clearButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("CLEAR");
        clearButton.setBorderPainted(false);
        clearButton.setFocusPainted(false);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGroup(mainPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(loanAmountLabel)
                                                        .addComponent(loanAmountField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 240,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(mainPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(durationLabel)
                                                        .addComponent(durationField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(scheduleScrollPane)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addComponent(totalRepaymentLabel)
                                                .addGap(10, 10, 10)
                                                .addComponent(totalRepaymentField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 140,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(totalInterestLabel)
                                                .addGap(10, 10, 10)
                                                .addComponent(totalInterestField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 140,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout
                                                .createSequentialGroup()
                                                .addGap(220, 220, 220)
                                                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(220, 220, 220)))
                                .addGap(20, 20, 20)));
        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(titleLabel)
                                .addGap(25, 25, 25)
                                .addGroup(
                                        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(loanAmountLabel)
                                                .addComponent(durationLabel))
                                .addGap(8, 8, 8)
                                .addGroup(
                                        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(loanAmountField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(durationField, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(scheduleScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(mainPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(totalRepaymentLabel)
                                        .addComponent(totalRepaymentField, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(totalInterestLabel)
                                        .addComponent(totalInterestField, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sets column widths and alignment on the repayment schedule table
     * to match the image layout exactly.
     */
    private void setUpTable() {
        javax.swing.table.TableColumnModel colModel = scheduleTable.getColumnModel();
        colModel.getColumn(0).setPreferredWidth(60); // MONTH
        colModel.getColumn(1).setPreferredWidth(160); // AMOUNT
        colModel.getColumn(2).setPreferredWidth(160); // INTEREST
        colModel.getColumn(3).setPreferredWidth(220); // MONTHLY REPAYMENT

        // Left-align all column headers and cells to match the image
        javax.swing.table.DefaultTableCellRenderer leftRenderer = new javax.swing.table.DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        for (int i = 0; i < scheduleTable.getColumnCount(); i++) {
            scheduleTable.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);
        }

        // Left-align the column headers as well
        ((javax.swing.table.DefaultTableCellRenderer) scheduleTable.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    }

    private void loanAmountFieldKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_loanAmountFieldKeyTyped
        char c = evt.getKeyChar();
        if (Character.isISOControl(c)) {
            return;
        }
        if (c == '.') {
            if (loanAmountField.getText().contains(".")) {
                JOptionPane.showMessageDialog(
                        null,
                        "Please enter numbers only in Loan Amount",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        } else if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please enter numbers only in Loan Amount",
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }// GEN-LAST:event_loanAmountFieldKeyTyped

    private void durationFieldKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_durationFieldKeyTyped
        char c = evt.getKeyChar();
        if (Character.isISOControl(c)) {
            return;
        }
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please enter numbers only in Loan Duration",
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }// GEN-LAST:event_durationFieldKeyTyped

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_calculateButtonActionPerformed
        calculateLoan();
    }// GEN-LAST:event_calculateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clearButtonActionPerformed
        loanAmountField.setText("");
        durationField.setText("");
        ((DefaultTableModel) scheduleTable.getModel()).setRowCount(0);
        totalRepaymentField.setText("");
        totalInterestField.setText("");
        loanAmountField.requestFocus();
    }// GEN-LAST:event_clearButtonActionPerformed

    /**
     * Validates inputs and calculates the repayment schedule.
     */
    private void calculateLoan() {
        try {
            String loanAmountStr = loanAmountField.getText().trim();
            String durationStr = durationField.getText().trim();

            // ── Empty-field validation ──────────────────────────────
            if (loanAmountStr.isEmpty() && durationStr.isEmpty()) {
                JOptionPane.showMessageDialog(
                        null,
                        "Kindly, fill in Loan Amount and Loan Duration to continue",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (loanAmountStr.isEmpty()) {
                JOptionPane.showMessageDialog(
                        null,
                        "Kindly, fill in Loan Amount to continue",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (durationStr.isEmpty()) {
                JOptionPane.showMessageDialog(
                        null,
                        "Kindly, fill in Loan Duration to continue",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            double loanAmount = Double.parseDouble(loanAmountStr);
            int months = Integer.parseInt(durationStr);

            if (loanAmount <= 0) {
                JOptionPane.showMessageDialog(
                        null,
                        "Error! Loan amount must be a positive number.",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (months <= 0) {
                JOptionPane.showMessageDialog(
                        null,
                        "Error! Loan duration must be a positive number of months.",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            double monthlyPrincipal = loanAmount / months;
            double interestRate = 1.5; // fixed interest rate

            // ── Populate table ──────────────────────────────────────
            DefaultTableModel tableModel = (DefaultTableModel) scheduleTable.getModel();
            tableModel.setRowCount(0); // clear previous rows

            double remainingBalance = loanAmount;
            double totalInterest = 0;
            double totalPayment = 0;

            for (int month = 1; month <= months; month++) {
                double monthlyInterest = (interestRate / 100.0) * remainingBalance;
                double monthlyPayment = monthlyPrincipal + monthlyInterest;

                totalInterest += monthlyInterest;
                totalPayment += monthlyPayment;

                tableModel.addRow(new Object[] {
                        month,
                        MONEY_FORMAT.format(monthlyPrincipal),
                        MONEY_FORMAT.format(monthlyInterest),
                        MONEY_FORMAT.format(monthlyPayment)
                });

                remainingBalance -= monthlyPrincipal;
            }

            totalRepaymentField.setText(MONEY_FORMAT.format(totalPayment));
            totalInterestField.setText(MONEY_FORMAT.format(totalInterest));

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please enter valid numeric values (e.g., 100000, 12).",
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    null,
                    "Unexpected error occurred!",
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Use the default System Look and Feel to match the image appearance */
        try {
            javax.swing.UIManager.setLookAndFeel(
                    javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanApp_W.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new LoanApp_W().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField durationField;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JTextField loanAmountField;
    private javax.swing.JLabel loanAmountLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane scheduleScrollPane;
    private javax.swing.JTable scheduleTable;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField totalInterestField;
    private javax.swing.JLabel totalInterestLabel;
    private javax.swing.JTextField totalRepaymentField;
    private javax.swing.JLabel totalRepaymentLabel;
    // End of variables declaration//GEN-END:variables
}
