/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */
import javax.swing.JOptionPane;

/**
 *
 * @author oyini
 */
public class AgeCalculator_W extends javax.swing.JFrame {

    /**
     * Creates new form AgeCalculator_W
     */
    public AgeCalculator_W() {
        initComponents();
        displayTodaysDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        todaysDateLabel = new javax.swing.JLabel();
        todaysDateValueLabel = new javax.swing.JLabel();
        birthdayLabel = new javax.swing.JLabel();
        birthdayField = new javax.swing.JTextField();
        birthmonthLabel = new javax.swing.JLabel();
        birthmonthField = new javax.swing.JTextField();
        birthyearLabel = new javax.swing.JLabel();
        birthyearField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        resultPanel = new javax.swing.JPanel();
        resultLabel = new javax.swing.JLabel();
        yearsField = new javax.swing.JTextField();
        yearsLabel = new javax.swing.JLabel();
        monthsField = new javax.swing.JTextField();
        monthsLabel = new javax.swing.JLabel();
        daysField = new javax.swing.JTextField();
        daysLabel = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Age Calculator");
        setResizable(false);

        headerPanel.setBackground(new java.awt.Color(190, 190, 190));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("AGE CALCULATOR");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleLabel)
                .addGap(15, 15, 15))
        );

        bodyPanel.setBackground(new java.awt.Color(190, 190, 190));

        todaysDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        todaysDateLabel.setText("TODAY'S DATE :");

        todaysDateValueLabel.setBackground(new java.awt.Color(245, 245, 245));
        todaysDateValueLabel.setText(" ");
        todaysDateValueLabel.setOpaque(true);

        birthdayLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        birthdayLabel.setText("ENTER BIRTHDAY");

        birthdayField.setToolTipText("Enter the day of the month you were born (1-31)");
        birthdayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayFieldActionPerformed(evt);
            }
        });
        birthdayField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                birthdayFieldKeyTyped(evt);
            }
        });

        birthmonthLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        birthmonthLabel.setText("ENTER BIRTHMONTH");

        birthmonthField.setToolTipText("Enter the month you were born (1-12)");
        birthmonthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthmonthFieldActionPerformed(evt);
            }
        });
        birthmonthField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                birthmonthFieldKeyTyped(evt);
            }
        });

        birthyearLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        birthyearLabel.setText("ENTER BIRTHYEAR");

        birthyearField.setToolTipText("Enter the 4-digit year you were born");
        birthyearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthyearFieldActionPerformed(evt);
            }
        });
        birthyearField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                birthyearFieldKeyTyped(evt);
            }
        });

        calculateButton.setBackground(new java.awt.Color(150, 150, 150));
        calculateButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        calculateButton.setForeground(new java.awt.Color(255, 255, 255));
        calculateButton.setText("CALCULATE AGE");
        calculateButton.setBorderPainted(false);
        calculateButton.setFocusPainted(false);
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        resultPanel.setBackground(new java.awt.Color(210, 210, 210));

        resultLabel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        resultLabel.setText("YOUR BIRTHDAY IS :");

        yearsField.setEditable(false);
        yearsField.setBackground(new java.awt.Color(235, 235, 235));
        yearsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        yearsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        yearsLabel.setText("YEARS");

        monthsField.setEditable(false);
        monthsField.setBackground(new java.awt.Color(235, 235, 235));
        monthsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        monthsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        monthsLabel.setText("MONTHS");

        daysField.setEditable(false);
        daysField.setBackground(new java.awt.Color(235, 235, 235));
        daysField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        daysLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        daysLabel.setText("DAYS");

        clearButton.setBackground(new java.awt.Color(139, 0, 0));
        clearButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("CLEAR");
        clearButton.setBorderPainted(false);
        clearButton.setFocusPainted(false);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(resultLabel)
                .addGap(20, 20, 20)
                .addComponent(yearsField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(yearsLabel)
                .addGap(20, 20, 20)
                .addComponent(monthsField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(monthsLabel)
                .addGap(20, 20, 20)
                .addComponent(daysField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(daysLabel)
                .addGap(20, 20, 20)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultLabel)
                    .addComponent(yearsField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearsLabel)
                    .addComponent(monthsField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthsLabel)
                    .addComponent(daysField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daysLabel)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthdayLabel)
                            .addComponent(birthdayField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthyearLabel)
                            .addComponent(birthyearField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthmonthLabel)
                            .addComponent(birthmonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(todaysDateLabel)
                        .addGap(18, 18, 18)
                        .addComponent(todaysDateValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(todaysDateLabel)
                    .addComponent(todaysDateValueLabel))
                .addGap(25, 25, 25)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(birthdayLabel)
                    .addComponent(birthmonthLabel))
                .addGap(6, 6, 6)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthmonthField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(birthyearLabel)
                        .addGap(6, 6, 6)
                        .addComponent(birthyearField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void birthdayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayFieldActionPerformed
        birthmonthField.requestFocus();
    }//GEN-LAST:event_birthdayFieldActionPerformed

    private void birthdayFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_birthdayFieldKeyTyped
        char c = evt.getKeyChar();
        if (Character.isISOControl(c)) {
            return;
        }
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please enter numbers only in Birthday",
                    "Error!",
                    JOptionPane.ERROR_MESSAGE
            );
            evt.consume();
        }
    }//GEN-LAST:event_birthdayFieldKeyTyped

    private void birthmonthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthmonthFieldActionPerformed
        birthyearField.requestFocus();
    }//GEN-LAST:event_birthmonthFieldActionPerformed

    private void birthmonthFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_birthmonthFieldKeyTyped
        char c = evt.getKeyChar();
        if (Character.isISOControl(c)) {
            return;
        }
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please enter numbers only in Birthmonth",
                    "Error!",
                    JOptionPane.ERROR_MESSAGE
            );
            evt.consume();
        }
    }//GEN-LAST:event_birthmonthFieldKeyTyped

    private void birthyearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthyearFieldActionPerformed
        calculateAge();
    }//GEN-LAST:event_birthyearFieldActionPerformed

    private void birthyearFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_birthyearFieldKeyTyped
        char c = evt.getKeyChar();
        if (Character.isISOControl(c)) {
            return;
        }
        if (!Character.isDigit(c)) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please enter numbers only in Birthyear",
                    "Error!",
                    JOptionPane.ERROR_MESSAGE
            );
            evt.consume();
        }
    }//GEN-LAST:event_birthyearFieldKeyTyped

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        calculateAge();
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearAll();
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * Displays today's date in the format: "Monday , 15 June 2026"
     */
    private void displayTodaysDate() {
        java.time.LocalDate today = java.time.LocalDate.now();
        String dayName = today.getDayOfWeek().getDisplayName(java.time.format.TextStyle.FULL, java.util.Locale.ENGLISH);
        String monthName = today.getMonth().getDisplayName(java.time.format.TextStyle.FULL, java.util.Locale.ENGLISH);
        String formatted = dayName + " , " + today.getDayOfMonth() + " " + monthName + " " + today.getYear();
        todaysDateValueLabel.setText(formatted);
    }

    private void clearAll() {
        birthdayField.setText("");
        birthmonthField.setText("");
        birthyearField.setText("");
        yearsField.setText("");
        monthsField.setText("");
        daysField.setText("");
        birthdayField.requestFocus();
    }

    /**
     * Calculates age using day/month borrowing logic.
     */
    private void calculateAge() {
        try {
            String dayStr = birthdayField.getText().trim();
            String monthStr = birthmonthField.getText().trim();
            String yearStr = birthyearField.getText().trim();

            if (dayStr.isEmpty() && monthStr.isEmpty() && yearStr.isEmpty()) {
                JOptionPane.showMessageDialog(
                        null,
                        "Kindly, fill in Birthday, Birthmonth and Birthyear to continue",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            if (dayStr.isEmpty()) {
                JOptionPane.showMessageDialog(
                        null,
                        "Kindly, fill in Birthday to continue",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            if (monthStr.isEmpty()) {
                JOptionPane.showMessageDialog(
                        null,
                        "Kindly, fill in Birthmonth to continue",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            if (yearStr.isEmpty()) {
                JOptionPane.showMessageDialog(
                        null,
                        "Kindly, fill in Birthyear to continue",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            int birthDay = Integer.parseInt(dayStr);
            int birthMonth = Integer.parseInt(monthStr);
            int birthYear = Integer.parseInt(yearStr);

            if (birthMonth < 1 || birthMonth > 12) {
                JOptionPane.showMessageDialog(
                        null,
                        "Invalid month entered. Month must be between 1 and 12.",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            java.time.LocalDate today = java.time.LocalDate.now();

            if (birthYear < 0 || birthYear > today.getYear()) {
                JOptionPane.showMessageDialog(
                        null,
                        "Invalid year entered. Please input valid year",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            java.time.YearMonth ym = java.time.YearMonth.of(birthYear, birthMonth);
            int daysInBirthMonth = ym.lengthOfMonth();

            if (birthDay < 1 || birthDay > daysInBirthMonth) {
                JOptionPane.showMessageDialog(
                        null,
                        "Invalid day entered for that month. Day must be between 1 and " + daysInBirthMonth + ".",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            java.time.LocalDate birthDate = java.time.LocalDate.of(birthYear, birthMonth, birthDay);

            if (birthDate.isAfter(today)) {
                JOptionPane.showMessageDialog(
                        null,
                        "Birth date cannot be in the future.",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            // Age calculation with day/month borrowing
            int currentYear = today.getYear();
            int currentMonth = today.getMonthValue();
            int currentDay = today.getDayOfMonth();

            if (currentDay < birthDay) {
                currentDay += daysInBirthMonth;
                currentMonth -= 1;
                if (currentMonth == 0) {
                    currentMonth = 12;
                    currentYear -= 1;
                }
            }

            if (currentMonth < birthMonth) {
                currentMonth += 12;
                currentYear -= 1;
            }

            int ageDays = currentDay - birthDay;
            int ageMonths = currentMonth - birthMonth;
            int ageYears = currentYear - birthYear;

            yearsField.setText(String.valueOf(ageYears));
            monthsField.setText(String.valueOf(ageMonths));
            daysField.setText(String.valueOf(ageDays));

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please enter numbers only in Birthday, Birthmonth and Birthyear",
                    "Error!",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    null,
                    "Unexpected error occurred!",
                    "Error!",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgeCalculator_W.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new AgeCalculator_W().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birthdayField;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JTextField birthmonthField;
    private javax.swing.JLabel birthmonthLabel;
    private javax.swing.JTextField birthyearField;
    private javax.swing.JLabel birthyearLabel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField daysField;
    private javax.swing.JLabel daysLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTextField monthsField;
    private javax.swing.JLabel monthsLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel todaysDateLabel;
    private javax.swing.JLabel todaysDateValueLabel;
    private javax.swing.JTextField yearsField;
    private javax.swing.JLabel yearsLabel;
    // End of variables declaration//GEN-END:variables
}
