import javax.swing.JOptionPane;

/**
 *
 * @author oyini
 */
public class BoylesLaw_W extends javax.swing.JFrame {

    /**
     * Creates new form BoylesLaw_W
     */
    public BoylesLaw_W() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        operationsPanel = new javax.swing.JPanel();
        findLabel = new javax.swing.JLabel();
        findComboBox = new javax.swing.JComboBox();
        p1Label = new javax.swing.JLabel();
        p1Field = new javax.swing.JTextField();
        p2Label = new javax.swing.JLabel();
        p2Field = new javax.swing.JTextField();
        v1Label = new javax.swing.JLabel();
        v1Field = new javax.swing.JTextField();
        v2Label = new javax.swing.JLabel();
        v2Field = new javax.swing.JTextField();
        bottomPanel = new javax.swing.JPanel();
        calculateButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        resultField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boyle's Law Calculator");
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("BOYLE'S LAW CALCULATOR");

        operationsPanel.setBackground(new java.awt.Color(136, 168, 191));
        operationsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("BOYLE'S LAW OPERATIONS"));

        findLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        findLabel.setText("FIND ................");

        findComboBox.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        findComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose One...", "Initial Pressure (P1)", "Initial Volume (V1)", "Final Pressure (P2)", "Final Volume (V2)" }));
        findComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findComboBoxActionPerformed(evt);
            }
        });

        p1Label.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        p1Label.setText("INITIAL PRESSURE (P1)");

        p1Field.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        p1Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                p1FieldKeyTyped(evt);
            }
        });

        p2Label.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        p2Label.setText("FINAL PRESSURE (P2)");

        p2Field.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        p2Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                p2FieldKeyTyped(evt);
            }
        });

        v1Label.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        v1Label.setText("INITIAL VOLUME (V1)");

        v1Field.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        v1Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                v1FieldKeyTyped(evt);
            }
        });

        v2Label.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        v2Label.setText("FINAL VOLUME (V2)");

        v2Field.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        v2Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                v2FieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout operationsPanelLayout = new javax.swing.GroupLayout(operationsPanel);
        operationsPanel.setLayout(operationsPanelLayout);
        operationsPanelLayout.setHorizontalGroup(
            operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(findLabel)
                    .addComponent(findComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(operationsPanelLayout.createSequentialGroup()
                        .addGroup(operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1Label)
                            .addComponent(p1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v1Label)
                            .addComponent(v1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p2Label)
                            .addComponent(p2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v2Label)
                            .addComponent(v2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        operationsPanelLayout.setVerticalGroup(
            operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(findLabel)
                .addGap(6, 6, 6)
                .addComponent(findComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1Label)
                    .addComponent(p2Label))
                .addGap(6, 6, 6)
                .addGroup(operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v1Label)
                    .addComponent(v2Label))
                .addGap(6, 6, 6)
                .addGroup(operationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bottomPanel.setBackground(new java.awt.Color(192, 192, 192));

        calculateButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        calculateButton.setText("CALCULATE");
        calculateButton.setBorder(null);
        calculateButton.setBorderPainted(false);
        calculateButton.setFocusPainted(false);
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        resultLabel.setText("THE RESULT =");

        resultField.setEditable(false);
        resultField.setBackground(new java.awt.Color(240, 240, 240));
        resultField.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N

        clearButton.setBackground(new java.awt.Color(185, 74, 74));
        clearButton.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("CLEAR");
        clearButton.setBorderPainted(false);
        clearButton.setFocusPainted(false);
        clearButton.setPreferredSize(new java.awt.Dimension(100, 25));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultLabel)
                            .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addComponent(resultLabel)
                        .addGap(6, 6, 6)
                        .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(operationsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(operationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void findComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        updateFieldStates();
    }// GEN-LAST:event_findComboBoxActionPerformed

    private void p1FieldKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_p1FieldKeyTyped
        validateNumberInput(evt, "Initial Pressure (P1)");
    }// GEN-LAST:event_p1FieldKeyTyped

    private void p2FieldKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_p2FieldKeyTyped
        validateNumberInput(evt, "Final Pressure (P2)");
    }// GEN-LAST:event_p2FieldKeyTyped

    private void v1FieldKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_v1FieldKeyTyped
        validateNumberInput(evt, "Initial Volume (V1)");
    }// GEN-LAST:event_v1FieldKeyTyped

    private void v2FieldKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_v2FieldKeyTyped
        validateNumberInput(evt, "Final Volume (V2)");
    }// GEN-LAST:event_v2FieldKeyTyped

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_calculateButtonActionPerformed
        calculateResult();
    }// GEN-LAST:event_calculateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clearButtonActionPerformed
        clearAll();
    }// GEN-LAST:event_clearButtonActionPerformed

    // -------------------------------------------------------------------------
    // Helper: validate that only digits and '.' are typed in an active field
    // -------------------------------------------------------------------------
    private void validateNumberInput(java.awt.event.KeyEvent evt, String fieldName) {
        char c = evt.getKeyChar();
        if (Character.isISOControl(c)) {
            return;
        }
        if (!(Character.isDigit(c) || c == '.')) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please enter numbers only in " + fieldName,
                    "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }

    
    private void updateFieldStates() {
        String selected = (String) findComboBox.getSelectedItem();

        setFieldActive(p1Field, true);
        setFieldActive(p2Field, true);
        setFieldActive(v1Field, true);
        setFieldActive(v2Field, true);

        if (selected != null) {
            switch (selected) {
                case "Initial Pressure (P1)":
                    setFieldActive(p1Field, false);
                    break;
                case "Initial Volume (V1)":
                    setFieldActive(v1Field, false);
                    break;
                case "Final Pressure (P2)":
                    setFieldActive(p2Field, false);
                    break;
                case "Final Volume (V2)":
                    setFieldActive(v2Field, false);
                    break;
                default:
                    break;
            }
        }

        p1Field.setText("");
        p2Field.setText("");
        v1Field.setText("");
        v2Field.setText("");
        resultField.setText("");
    }

    private void setFieldActive(javax.swing.JTextField field, boolean active) {
        field.setEditable(active);
        field.setBackground(active
                ? java.awt.Color.WHITE
                : new java.awt.Color(200, 200, 200));
    }

    
    private void calculateResult() {
        try {
            String selected = (String) findComboBox.getSelectedItem();

            if (selected == null || selected.equals("Choose One...")) {
                JOptionPane.showMessageDialog(null,
                        "Please select what you want to calculate from the FIND dropdown.",
                        "No Selection",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            switch (selected) {

                case "Initial Pressure (P1)": {
                    // P1 = (P2 * V2) / V1
                    if (p2Field.getText().trim().isEmpty()
                            || v1Field.getText().trim().isEmpty()
                            || v2Field.getText().trim().isEmpty()) {
                        showMissingFieldsError("Final Pressure (P2), Initial Volume (V1), and Final Volume (V2)");
                        return;
                    }
                    double p2 = Double.parseDouble(p2Field.getText().trim());
                    double v1 = Double.parseDouble(v1Field.getText().trim());
                    double v2 = Double.parseDouble(v2Field.getText().trim());
                    if (v1 == 0) {
                        showDivisionByZeroError("Initial Volume (V1)");
                        return;
                    }
                    displayResult((p2 * v2) / v1);
                    break;
                }

                case "Initial Volume (V1)": {
                    // V1 = (P2 * V2) / P1
                    if (p1Field.getText().trim().isEmpty()
                            || p2Field.getText().trim().isEmpty()
                            || v2Field.getText().trim().isEmpty()) {
                        showMissingFieldsError("Initial Pressure (P1), Final Pressure (P2), and Final Volume (V2)");
                        return;
                    }
                    double p1 = Double.parseDouble(p1Field.getText().trim());
                    double p2 = Double.parseDouble(p2Field.getText().trim());
                    double v2 = Double.parseDouble(v2Field.getText().trim());
                    if (p1 == 0) {
                        showDivisionByZeroError("Initial Pressure (P1)");
                        return;
                    }
                    displayResult((p2 * v2) / p1);
                    break;
                }

                case "Final Pressure (P2)": {
                    // P2 = (P1 * V1) / V2
                    if (p1Field.getText().trim().isEmpty()
                            || v1Field.getText().trim().isEmpty()
                            || v2Field.getText().trim().isEmpty()) {
                        showMissingFieldsError("Initial Pressure (P1), Initial Volume (V1), and Final Volume (V2)");
                        return;
                    }
                    double p1 = Double.parseDouble(p1Field.getText().trim());
                    double v1 = Double.parseDouble(v1Field.getText().trim());
                    double v2 = Double.parseDouble(v2Field.getText().trim());
                    if (v2 == 0) {
                        showDivisionByZeroError("Final Volume (V2)");
                        return;
                    }
                    displayResult((p1 * v1) / v2);
                    break;
                }

                case "Final Volume (V2)": {
                    // V2 = (P1 * V1) / P2
                    if (p1Field.getText().trim().isEmpty()
                            || v1Field.getText().trim().isEmpty()
                            || p2Field.getText().trim().isEmpty()) {
                        showMissingFieldsError("Initial Pressure (P1), Initial Volume (V1), and Final Pressure (P2)");
                        return;
                    }
                    double p1 = Double.parseDouble(p1Field.getText().trim());
                    double v1 = Double.parseDouble(v1Field.getText().trim());
                    double p2 = Double.parseDouble(p2Field.getText().trim());
                    if (p2 == 0) {
                        showDivisionByZeroError("Final Pressure (P2)");
                        return;
                    }
                    displayResult((p1 * v1) / p2);
                    break;
                }

                default:
                    JOptionPane.showMessageDialog(null,
                            "Unknown selection. Please choose a valid option.",
                            "Error!",
                            JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,
                    "One or more input fields contain an invalid number. Please check your values.",
                    "Invalid Number",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "An unexpected error occurred: " + ex.getMessage(),
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    
    private void displayResult(double value) {
        String resultStr = (value == (long) value)
                ? String.format("%d", (long) value)
                : String.format("%.4f", value);
        resultField.setText(resultStr);
        resultField.setForeground(new java.awt.Color(0, 102, 0));
    }

   
    private void showMissingFieldsError(String requiredFields) {
        JOptionPane.showMessageDialog(null,
                "Please fill in the following required fields:\n" + requiredFields,
                "Missing Values",
                JOptionPane.ERROR_MESSAGE);
    }

    private void showDivisionByZeroError(String fieldName) {
        JOptionPane.showMessageDialog(null,
                fieldName + " cannot be zero.\nDivision by zero is not allowed.",
                "Invalid Value",
                JOptionPane.ERROR_MESSAGE);
    }

   
    private void clearAll() {
        findComboBox.setSelectedIndex(0);
        p1Field.setText("");
        p2Field.setText("");
        v1Field.setText("");
        v2Field.setText("");
        resultField.setText("");
        resultField.setForeground(new java.awt.Color(0, 0, 0));
        setFieldActive(p1Field, true);
        setFieldActive(p2Field, true);
        setFieldActive(v1Field, true);
        setFieldActive(v2Field, true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoylesLaw_W.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }

        java.awt.EventQueue.invokeLater(() -> new BoylesLaw_W().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox findComboBox;
    private javax.swing.JLabel findLabel;
    private javax.swing.JPanel operationsPanel;
    private javax.swing.JTextField p1Field;
    private javax.swing.JLabel p1Label;
    private javax.swing.JTextField p2Field;
    private javax.swing.JLabel p2Label;
    private javax.swing.JTextField resultField;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField v1Field;
    private javax.swing.JLabel v1Label;
    private javax.swing.JTextField v2Field;
    private javax.swing.JLabel v2Label;
    // End of variables declaration//GEN-END:variables
}