/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */
import javax.swing.JOptionPane;

/**
 *
 * @author oyini
 */
public class Sum2_W extends javax.swing.JFrame {

    /**
     * Creates new form Sum2_W
     */
    public Sum2_W() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        divider = new javax.swing.JSeparator();
        firstNumberLabel = new javax.swing.JLabel();
        firstNumberField = new javax.swing.JTextField();
        secondNumberLabel = new javax.swing.JLabel();
        secondNumberField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        resultTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sum2 App");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(26, 53, 74));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Sum2 App");

        divider.setForeground(new java.awt.Color(100, 149, 180));

        firstNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        firstNumberLabel.setForeground(new java.awt.Color(220, 230, 240));
        firstNumberLabel.setText("First Number");

        firstNumberField.setBackground(new java.awt.Color(52, 100, 140));
        firstNumberField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNumberField.setForeground(new java.awt.Color(255, 255, 255));
        firstNumberField.setCaretColor(new java.awt.Color(255, 255, 255));
        firstNumberField.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 10, 6, 10));
        firstNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNumberFieldKeyTyped(evt);
            }
        });

        secondNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        secondNumberLabel.setForeground(new java.awt.Color(220, 230, 240));
        secondNumberLabel.setText("Second Number");

        secondNumberField.setBackground(new java.awt.Color(52, 100, 140));
        secondNumberField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        secondNumberField.setForeground(new java.awt.Color(255, 255, 255));
        secondNumberField.setCaretColor(new java.awt.Color(255, 255, 255));
        secondNumberField.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 10, 6, 10));
        secondNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                secondNumberFieldKeyTyped(evt);
            }
        });

        calculateButton.setBackground(new java.awt.Color(70, 140, 190));
        calculateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        calculateButton.setForeground(new java.awt.Color(255, 255, 255));
        calculateButton.setText("Calculate Sum");
        calculateButton.setBorderPainted(false);
        calculateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calculateButton.setFocusPainted(false);
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        resultLabel.setForeground(new java.awt.Color(220, 230, 240));
        resultLabel.setText("Result");

        resultTxt.setEditable(false);
        resultTxt.setFocusable(false);
        resultTxt.setBackground(new java.awt.Color(52, 100, 140));
        resultTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resultTxt.setForeground(new java.awt.Color(255, 255, 255));
        resultTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 10, 6, 10));
        resultTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(divider, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(firstNumberLabel)
                    .addComponent(firstNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(secondNumberLabel)
                    .addComponent(secondNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(calculateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(resultLabel)
                    .addComponent(resultTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titleLabel)
                .addGap(10, 10, 10)
                .addComponent(divider, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(firstNumberLabel)
                .addGap(8, 8, 8)
                .addComponent(firstNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(secondNumberLabel)
                .addGap(8, 8, 8)
                .addComponent(secondNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(resultLabel)
                .addGap(8, 8, 8)
                .addComponent(resultTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        try {
            String firstNumberStr, secondNumberStr;
            double firstNumber, secondNumber, result;

            firstNumberStr = firstNumberField.getText().trim();
            secondNumberStr = secondNumberField.getText().trim();

            
            if ((firstNumberStr.isEmpty()) && (secondNumberStr.isEmpty())) {
                JOptionPane.showMessageDialog(
                        null,
                        "Kindly, fill in First Number and Second Number to continue",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            if (firstNumberStr.isEmpty()) {
                JOptionPane.showMessageDialog(
                        null,
                        "Kindly, fill in First Number to continue",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            if (secondNumberStr.isEmpty()) {
                JOptionPane.showMessageDialog(
                        null,
                        "Kindly, fill in Second Number to continue",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            firstNumber = Double.parseDouble(firstNumberStr);
            secondNumber = Double.parseDouble(secondNumberStr);
            result = firstNumber + secondNumber;
            resultTxt.setText(String.valueOf(result));

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please enter numbers only in First Number and Second Number",
                    "Error!",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    null,
                    "Unexpected error occurred!",
                    "Error!",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void firstNumberFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNumberFieldKeyTyped
        char c = evt.getKeyChar();
        if (Character.isISOControl(c)) {
            return; 
        }
        if (!(Character.isDigit(c) || c == '.' || c == '-')) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please enter numbers only in First Number",
                    "Error!",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_firstNumberFieldKeyTyped

    private void secondNumberFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secondNumberFieldKeyTyped
        char c = evt.getKeyChar();
        if (Character.isISOControl(c)) {
            return; 
        }
        if (!(Character.isDigit(c) || c == '.' || c == '-')) {
            JOptionPane.showMessageDialog(
                    null,
                    "Please enter numbers only in Second Number",
                    "Error!",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_secondNumberFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sum2_W.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Sum2_W().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JSeparator divider;
    private javax.swing.JTextField firstNumberField;
    private javax.swing.JLabel firstNumberLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField resultTxt;
    private javax.swing.JTextField secondNumberField;
    private javax.swing.JLabel secondNumberLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
